### Day Objectives

- Practice test on frequency distribution and combinatorics

- File/Data Encryption and Decryption

- Python Libraries for Data Science

- scipy.org

### Numpy Library

- processing N-Dimensional array

In [4]:
import numpy as np

li=[1,2,3,4,5,6,7]

a=np.array(li)
a

array([1, 2, 3, 4, 5, 6, 7])

In [5]:
li=[1,2,3,4,5,'a']
a=np.array(li)
a

array(['1', '2', '3', '4', '5', 'a'], dtype='<U11')

In [7]:
li=[1,2,3,4,5]
a=np.array(li)
b=np.arange(15)
b

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [8]:
# to generate random numbers
rn=np.random.randint(0,100,size=10)
rn

array([54, 91, 14, 29, 56, 11, 53, 34,  3, 38])

In [32]:
# three dimensional array
m3=np.random.randint(0,2,size=(3,3,3))
print(m3)
print(m3.size)
print(m3.ndim)
print(m3.shape)
print(m3.dtype)
print(m3.itemsize)
print(m3.nbytes)


[[[0 1 1]
  [1 0 1]
  [0 0 1]]

 [[0 1 1]
  [1 0 0]
  [0 0 1]]

 [[0 0 0]
  [0 0 0]
  [0 0 1]]]
27
3
(3, 3, 3)
int32
4
108


In [35]:
m1=np.random.randint(0,2,size=(3,3))
m1

array([[1, 1, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [36]:
m1[:2, :3]#sub array by slicing

array([[1, 1, 1],
       [0, 1, 0]])

In [37]:
m1[:3,::2]#sub array by slicing

array([[1, 1],
       [0, 0],
       [1, 1]])

In [38]:
m1[::-1,::-1]# reversing 
m1

array([[1, 1, 1],
       [0, 1, 0],
       [1, 0, 1]])

In [39]:
print(m1)

[[1 1 1]
 [0 1 0]
 [1 0 1]]


In [40]:
print(m1[0])#m1[0:]

[1 1 1]


In [42]:
print(m1[:2,:2]) # sub array

[[1 1]
 [0 1]]


In [47]:
b.reshape(5,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

###  Pandas


Use Cases

- Data Cleaning

- Data Transformation

- Data Analysis

Notations

- Series

- DataFrames



In [4]:
import pandas as pd

internal1={'s1':20,'s2':19,'s3':5,'s4':25,'s5':17}

interanl1=pd.Series(internal1)
interanl2={'s1':21,'s2':19,'s3':15,'s4':25,'s5':17}
interanl2=pd.Series(interanl2)
interanl2

s1    21
s2    19
s3    15
s4    25
s5    17
dtype: int64

In [7]:
final={'Internal':interanl1,'Internal2':interanl2}

final=pd.DataFrame(final)
final['Internal']

s1    20
s2    19
s3     5
s4    25
s5    17
Name: Internal, dtype: int64

In [8]:
final.columns

Index(['Internal', 'Internal2'], dtype='object')

In [11]:
final.values  # Lists of all rows

array([[20, 21],
       [19, 19],
       [ 5, 15],
       [25, 25],
       [17, 17]], dtype=int64)

In [12]:
final.values[4]

array([17, 17], dtype=int64)

In [13]:
final.values[2,0]  #final.values[2][0]

5

In [26]:
for row in final.values:
    print('Interal1 -' ,+row[0],'Internal2 -',+row[1])

Interal1 - 20 Internal2 - 21
Interal1 - 19 Internal2 - 19
Interal1 - 5 Internal2 - 15
Interal1 - 25 Internal2 - 25
Interal1 - 17 Internal2 - 17
Interal1 - 1 Internal2 - 2
Interal1 - 1 Internal2 - 2


In [25]:
final.loc['s6']=[1,2]
final

Internal  Internal2
s1        20         21
s2        19         19
s3         5         15
s4        25         25
s5        17         17
5          1          2
s6         1          2

In [27]:
final.drop(5)

Internal  Internal2
s1        20         21
s2        19         19
s3         5         15
s4        25         25
s5        17         17
s6         1          2

In [2]:
#reading csv filedata
import pandas as pd
filepath='DataFiles/Income.csv'
IncomeDf=pd.read_csv(filepath)
IncomeDf

GEOID       State   2005   2006   2007   2008   2009   2010   2011  \
0  04000US01     Alabama  37150  37952  42212  44476  39980  40933  42590   
1  04000US02      Alaska  55891  56418  62993  63989  61604  57848  57431   
2  04000US04     Arizona  45245  46657  62993  46914  45739  46896  48621   
3  04000US05    Arkansas  36658  37057  40795  39586  36538  38587  41302   
4  04000US06  California  51755  55319  55734  57014  56134  54283  53367   

    2012   2013  
0  43464  41381  
1  63648  61137  
2  47044  50602  
3  39018  39919  
4  57020  57528

In [3]:
# Extract income of all states in 2013

# California:57528

#IncomeDf.values
for row in IncomeDf.values:
    print(row[1],':',row[-1])
    

Alabama : 41381
Alaska : 61137
Arizona : 50602
Arkansas : 39919
California : 57528


In [8]:
# Average Income of Arizona
sum=0
for i in range(2,11):
    sum+=IncomeDf.values[2][i]
sum/len(IncomeDf.values[2][2:])

48967.88888888889

In [36]:
# average of all states in 2012
sum=0
for row in IncomeDf.values:
    sum+=row[-2]
sum/len(IncomeDf.values)

    

50038.8